db_locate: localhost
port: 3306
db_name: IUHStudent
db_username: springuser
db_password: saPassword12@

spring:
  jpa:
    hibernate:
      ddl-auto: create
    database: mysql
    show-sql: true

  datasource:
    url: jdbc:mysql://${db_locate}:${port}/${db_name}
    username: ${db_username}
    password: ${db_password}
    driver-class-name: com.mysql.cj.jdbc.Driver

graphql:
  servlet:
    mapping: /graphql
    enabled: true
    exception-handlers-enabled: true
    context-setting: per_query_with_instrumentation
    tracingEnabled: false
    corsEnabled: true

graphiql:
  headers:
    Authorization: Bearer my-generated-token
  mapping: /graphiql
  endpoint:
    graphql: /graphql
    subscriptions: /subscriptions
  subscriptions:
    reconnect: false
    timeout: 30
  enabled: true
  pageTitle: GraphiQL
  cdn:
    enabled: false
    version: 0.13.0