graphql:
  servlet:
    mapping: /graphql
    enabled: true
    exception-handlers-enabled: true
    context-setting: per_query_with_instrumentation
    tracingEnabled: false
    corsEnabled: true

graphiql:
  mapping: /graphiql
  endpoint:
    graphql: /graphql
    subscriptions: /subscriptions
  subscriptions:
    reconnect: false
    timeout: 30
  enabled: true
  pageTitle: GraphiQL
  cdn:
    enabled: false
    version: 0.13.0